ANTHROPIC_API_KEY = "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"

POLYGON_KEY = "Ixa9NNtmgLzlFBtjaA0oBZVHHepnqU4E"

FINNHUB_KEY = "d5ciothr01qgl5oncdagd5ciothr01qgl5oncdb0"

BPIQ_API_KEY = "bda363d6f6beba9c6402c2a1637940b62beef66c"